version: "3.9"
services:
  db:
    image: postgres:18
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_vacancy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    mem_limit: 512m  
    cpus: 1.0

volumes:
  postgres_data:
    driver: local